### ISSUE TITLE
Animated Website

### ISSUE THREAD

**Issue by ritika728** [mrsparkle-70/Emotion-detection-using-JS#109]
Hey @mrsparkle-70 I would like to open this issue under JWOC. Animations makes a website look attractive. On navigating to a different page, the fade animations enhances user experience as the text would take a short period of time to appear. I would like to make the entire website animated wherever possible.

**Comment by mrsparkle-70** [comment]
Animations are alright 

But I don't want any type of delay while navigating 
Is it possible ?

**Comment by ritika728** [comment]
I would keep the animation transitioning time to 2-3 seconds. Will that be fine ?

**Comment by mrsparkle-70** [comment]
Actually I don't like any delay while navigating be it of 2..3 sec

I would suggest you to add some animations on the page itself

Rather than animations while navigating

If you are too interested in animations while navigating

First I would suggest you to show me a demo
Then only I can decide

Definitely this will be labeled as Hard

**Comment by ritika728** [comment]
https://www.ieeerssc.tech/ 
@mrsparkle-70 This is one of the websites prepared by me. In this, I added the animations in such a way that the particular section was appearing using fade animations on scrolling to that specific portion.

Since emotion detector website has different pages instead of a single one and there isn't much text, I was thinking of implementing the same on navigating. I'll add the animations to specific pages and also the hover effects and typewriter effect on the available text on required pages
